Convert hand rolled XML document generation to use the ElementTree module.
google/capirca pull request #253
Opened 2021-03-18 17:30 UTC by kevinsteves

Functionally equivalent to previous with exceptions:

    remove XML declaration as not needed

    change config version to 8.1.0 (earliest supported PAN-OS)

    don't indent XML as this can be performed with other tooling
    (e.g., xmllint)

    application groups are not currently used and the XML was
    not rendered correctly, so remove XML generation for now.

2021-03-19 00:15 UTC, rdsharma requested changes

2021-03-19 00:15 UTC, rdsharma commented on capirca/lib/paloaltofw.py
> -        etree.tostring(app_entries)).toprettyxml(indent="  ")
Can we add this functionality back in?

2021-03-19 16:25 UTC, kevinsteves commented on capirca/lib/paloaltofw.py
> -        etree.tostring(app_entries)).toprettyxml(indent="  ")
Added ident of the XML document.

2021-03-30 05:02 UTC, rdsharma approved these changes
This looks good, nice work! Will wait until @abhindes reviews as well (for syntax correctness) to pull this in.

Like I mentioned before, we'll have to do something to expose the etree object to tests later on so that we can check the DOM itself rather than the rendered output, but that can come in a later CL if you prefer.

2021-03-30 21:04 UTC, abhindes approved these changes
Looks good to me. I loved how easy it was to view the diffs as well.

Great work Kevin!

2021-03-30 22:09 UTC, merged